theme = "molokai"

[editor]
auto-save = true
auto-format = true
"cursorline" = true
bufferline = "multiple"
line-number = "relative"
end-of-line-diagnostics = "hint"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.whitespace]
render = "none"
character = "▏"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]

[editor.lsp]
enable = true
display-messages = false
auto-signature-help = true
display-inlay-hints = false
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true
